services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./documentos:/data/documentos
      - ./tmp:/data/tmp
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=jesus
      - N8N_BASIC_AUTH_PASSWORD=airtrace
      - NODE_FUNCTION_ALLOW_EXTERNAL=@qdrant/qdrant-js,axios,fetch,csv2xlsx
      - TZ=Europe/Madrid
    networks:
      iot_network:
        ipv4_address: 172.25.0.5

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    container_name: ollama
    restart: unless-stopped
    networks:
      iot_network:
        ipv4_address: 172.25.0.6

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      iot_network:
        ipv4_address: 172.25.0.7

volumes:
  n8n_data:
  ollama_data:
  qdrant_storage:

networks:
  iot_network:
    external: true                       # Esto le dice a Docker que la red ya existe
    name: flowguard-compose_iot_network  # Usa el nombre de la red que ya existe


#docker-compose up --build
#docker exec -it ollama ollama pull llama3.1
#docker exec -it ollama ollama pull nomic-embed-text
#docker-compose down
#docker-compose up

