services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./documentos:/data/documentos
      - ./tmp:/data/
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=jesus
      - N8N_BASIC_AUTH_PASSWORD=airtrace
      - NODE_FUNCTION_ALLOW_EXTERNAL=@qdrant/qdrant-js,axios,fetch,csv2xlsx
      - TZ=Europe/Madrid

  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    container_name: ollama
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_storage:/qdrant/storage

  unstructured:
    image: quay.io/unstructured-io/unstructured-api:latest
    container_name: unstructured
    ports:
      - "8000:8000"
    environment:
      UNSTRUCTURED_API_CFG_FAST: "true"     # reduce descarga de modelos a demanda
    volumes:
      - ./unstructured_cache:/home/unstructured
    restart: unless-stopped

  weave-worker:
    build:
      context: ./weave-worker   # ruta donde está el Dockerfile
      dockerfile: Dockerfile        # opcional, si el fichero se llama distinto cámbialo
    image: weave-worker:v1
    container_name: weave-worker
    environment:
      - WEAVE_WANDB_KEY=${WEAVE_WANDB_KEY}
      - WEAVE_PROJECT=${WEAVE_PROJECT}
    ports:
      - "7000:7000"
    restart: unless-stopped

volumes:
  n8n_data:
  ollama_data:
  qdrant_storage:


#docker-compose up --build
#ccccccc
#docker exec -it ollama ollama pull mistral:instruct
#docker exec -it ollama ollama pull nomic-embed-text
#docker-compose down
#sudo docker compose down --remove-orphans
#docker-compose up

