services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./documentos:/data/documentos
      - ./tmp:/data/tmp
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=jesus
      - N8N_BASIC_AUTH_PASSWORD=airtrace
      - NODE_FUNCTION_ALLOW_EXTERNAL=@qdrant/qdrant-js,axios,fetch,csv2xlsx
      - TZ=Europe/Madrid
    networks:
      iot_network:
        ipv4_address: 172.25.0.5

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    container_name: ollama
    restart: unless-stopped
    networks:
      iot_network:
        ipv4_address: 172.25.0.6

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      iot_network:
        ipv4_address: 172.25.0.7

  unstructured:
    image: quay.io/unstructured-io/unstructured-api:latest
    container_name: unstructured
    ports:
      - "8000:8000"
    environment:
      UNSTRUCTURED_API_CFG_FAST: "true"     # reduce descarga de modelos a demanda
    volumes:
      - ./unstructured_cache:/home/unstructured
    restart: unless-stopped
    networks:
      iot_network:
        ipv4_address: 172.25.0.9

  weave-worker:
    build:
      context: ./weave-worker   # ruta donde está el Dockerfile
      dockerfile: Dockerfile        # opcional, si el fichero se llama distinto cámbialo
    image: weave-worker:v1
    container_name: weave-worker
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WEAVE_PROJECT=n8n-RAG
    ports:
      - "7000:7000"
    restart: unless-stopped
    networks:
      iot_network:
        ipv4_address: 172.25.0.8

volumes:
  n8n_data:
  ollama_data:
  qdrant_storage:

networks:
  iot_network:
    external: true                       # Esto le dice a Docker que la red ya existe
    name: flowguard-compose_iot_network  # Usa el nombre de la red que ya existe


#docker-compose up --build
#sudo docker compose up --build
#docker exec -it ollama ollama pull mistral:instruct
#docker exec -it ollama ollama pull nomic-embed-text
#docker-compose down
#sudo docker compose down --remove-orphans
#docker-compose up

